### ISSUE TITLE
ㅌㅂ가 숫자만 입력을 받나요 아니면 문자열도 입력을 받을 수 있나요?

### ISSUE THREAD

**Issue by kdh8219** [assertive-lang/asserlang#38]
숫자만 입력을 받는다면 문자열이 입력되었을때 에러는 뭘로 해야 할까요?

**Comment by sujang958** [comment]
둘 다 입력 받습니다

**Comment by sangchoo1201** [comment]
엥 그러면 예를 들어 "1"을 입력하면 이게 숫자인지 문자열인지 구분은 어떻게 하나요?

**Comment by sangchoo1201** [comment]
그렇다면 숫자 입력과 문자 입력을 구분하는 기준은 무엇인가요

**Comment by kdh8219** [comment]
그리고 변수에 문자를 1글자만 담을 수 있지 않나요?

**Comment by kdh8219** [comment]
그렇다면 문자입력과 숫자입력을 구분하는것은 어떤가요?
엇쩔티비/젓쩔티비라던지

**Comment by kdh8219** [comment]
![image](https://user-images.githubusercontent.com/65698239/156000110-d0fb3a90-2c82-4a1b-b34a-71992bae9667.png)

**Comment by chul0721** [comment]
"않는 문서" => "않는 문자"
오타 정정합니다.
