### ISSUE TITLE
출력 시 동작

### ISSUE THREAD

**Issue by Ko-TTae** [assertive-lang/asserlang#49]
변수 (어, 쩔, 티, 비) 각각에 할당된 값이 (1, 2, 3, 4)라고 할 때

`ㅇㅉ어 쩔 티 비`의 실행 결과가 `1~2~3~4`인데 의도한 동작인가요?

**Comment by chul0721** [comment]
우선 이슈를 남겨주셔서 감사합니다.
어쩔랭은 기본적으로 띄어쓰기 단위를 사용하지 않고 물결 기호(~)를 사용합니다.
또한 ㅇㅉ은 하나의 변수만을 출력하기 때문에 ㅇㅉ어 ㅇㅉ절 등 따로 출력하시는게 정확합니다.

**Comment by chul0721** [comment]
해결되셨다면 해당 이슈를 닫도록 하겠습니다.
